# Generated by Django 4.2.3 on 2023-08-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_profilephoto_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilephoto',
            old_name='user',
            new_name='user_profile',
        ),
    ]
