# Generated by Django 4.2.3 on 2023-08-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_user_profilephoto_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
