# Generated by Django 4.2.3 on 2023-08-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_profilephoto_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='url',
            field=models.CharField(default='main_app/static/images/defaults/user1.jpg', max_length=200),
        ),
    ]
