# Generated by Django 4.2.3 on 2023-08-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_profilephoto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='url',
            field=models.CharField(default='main_app/static/images/user1.jpg', max_length=200),
        ),
    ]
